qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/archaea.1.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/archaea.2.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/archaea.3.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.100.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.101.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.10.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.102.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.103.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.104.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.105.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.106.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.11.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.11.2.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.1.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.12.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.12.2.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.13.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.13.2.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.14.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.15.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.16.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.17.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.17.2.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.18.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.19.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.20.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.21.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.2.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.22.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.2.2.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.23.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.24.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.25.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.26.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.27.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.28.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.29.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.29.2.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.30.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.31.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.3.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.32.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.33.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.34.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.34.2.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.35.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.36.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.37.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.38.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.39.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.40.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.41.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.4.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.42.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.4.2.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.43.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.44.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.45.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.46.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.46.2.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.47.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.47.2.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.48.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.48.2.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.49.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.49.2.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.50.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.51.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.51.2.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.5.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.52.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.53.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.54.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.55.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.56.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.57.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.58.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.59.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.60.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.61.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.6.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.62.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.6.2.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.63.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.64.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.65.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.66.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.67.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.68.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.69.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.70.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.71.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.7.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.72.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.73.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.74.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.75.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.76.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.77.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.78.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.79.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.80.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.81.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.8.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.82.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.83.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.84.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.85.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.86.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.87.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.88.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.89.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.90.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.91.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.9.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.92.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.9.2.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.93.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.94.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.95.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.96.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.97.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.98.1.genomic.fna
qsub -V -cwd -b y script/sim.0104.builddb.pl /export2/home/uesu/db/refseq/bac_arch/bacteria.99.1.genomic.fna
